export const tipsConfig = [
  // ── Tips awal (dari file asli) ──
  "Pecahan 1/2 sama nilainya dengan 2/4 lho!",
  "Dalam penjumlahan pecahan, penyebutnya harus disamakan terlebih dahulu sebelum dijumlahkan.",
  "Garis pada pecahan memiliki arti yang sama dengan 'dibagi'.",
  "Jika pembilang dan penyebut memiliki nilai yang sama, maka nilai pecahan tersebut adalah 1.",
  "Berlatih soal secara rutin dapat meningkatkan pemahaman matematikamu dengan cepat!",
  "Matematika itu menyenangkan jika kamu menganggapnya seperti sebuah permainan teka-teki.",
  "Pecahan senilai adalah pecahan yang nilainya tidak akan berubah walaupun pembilang dan penyebutnya dikalikan atau dibagi dengan bilangan yang sama.",

  // ── Konsep dan makna pecahan ──
  "Pecahan adalah cara menyatakan bagian dari keseluruhan.",
  "Semua bagian dalam sebuah pecahan harus sama besar. Kalau tidak sama besar, itu bukan pecahan!",
  "Angka di atas garis pecahan disebut pembilang, angka di bawah garis disebut penyebut.",
  "Penyebut menunjukkan berapa banyak bagian sama besar yang ada dalam satu keseluruhan.",
  "Pembilang menunjukkan berapa banyak bagian yang kita ambil atau warnai.",
  "Bingung membedakan pembilang dan penyebut? Ingat saja: pembilang di atas, penyebut di bawah.",
  "Menggambar bulatan atau persegi lalu membaginya bisa membantumu memahami pecahan.",
  "Pizza, kue, dan cokelat adalah contoh yang bagus untuk membayangkan pecahan dalam kehidupan sehari-hari.",
  "Satu utuh bisa ditulis sebagai pecahan, misalnya 3/3, 4/4, atau 8/8.",
  "Pecahan yang pembilangnya lebih kecil dari penyebut nilainya kurang dari 1.",
  "Semakin banyak sebuah benda dibagi, semakin kecil setiap potongannya.",
  "Pecahan tidak hanya ada di buku. Saat membagi roti atau mengukur bahan kue, kamu sedang memakai pecahan!",
  "Penyebut tidak boleh nol, karena kita tidak bisa membagi sesuatu menjadi nol bagian.",
  "Saat mewarnai gambar pecahan, hitung dulu seluruh bagiannya sebelum menghitung bagian yang diwarnai.",
  "Pecahan 1/2 artinya satu bagian dari dua bagian yang sama besar.",

  // ── Membaca dan menuliskan pecahan ──
  'Pecahan dibaca pembilang dulu, lalu kata "per", lalu penyebut. Contoh: 3/7 dibaca "tiga per tujuh".',
  'Pecahan 1/2 sering dibaca "setengah", 1/3 dibaca "sepertiga", dan 1/4 dibaca "seperempat".',
  'Pecahan 3/4 bisa dibaca "tiga per empat" atau "tiga perempat".',
  'Saat menulis pecahan dari bacaannya, bilangan sebelum kata "per" ditulis di atas garis.',
  '"Tiga per tujuh" ditulis 3/7, bukan 37. Jangan lupa garis pecahannya!',
  "2/5 dan 5/2 adalah pecahan yang berbeda, jadi posisi angkanya tidak boleh tertukar.",
  "Tulis garis pecahan dengan lurus dan rapi supaya pembilang dan penyebutnya mudah dibaca.",
  "Latihlah membaca pecahan dengan suara keras agar kamu terbiasa dengan cara bacanya.",
  'Pecahan 7/10 dibaca "tujuh per sepuluh".',
  '"Setengah kilo" gula artinya 1/2 kilogram. Ternyata pecahan ada di dapur juga!',

  // ── Membandingkan pecahan ──
  'Simbol > berarti "lebih besar dari", simbol < berarti "lebih kecil dari", dan simbol = berarti "sama dengan".',
  "Mulut simbol > dan < selalu terbuka ke arah bilangan yang lebih besar.",
  "Jika penyebutnya sama, bandingkan saja pembilangnya. Pembilang lebih besar berarti pecahan lebih besar.",
  "3/5 lebih besar dari 2/5 karena penyebutnya sama dan 3 lebih besar dari 2.",
  "Jika pembilangnya sama, pecahan dengan penyebut lebih kecil nilainya lebih besar.",
  "1/3 lebih besar dari 1/6, karena kue yang dibagi 3 punya potongan lebih besar daripada kue yang dibagi 6.",
  "Penyebut yang besar tidak selalu berarti pecahannya besar. Kadang justru sebaliknya!",
  "Sebelum membandingkan pecahan berpenyebut berbeda, samakan dulu penyebutnya.",
  "Gunakan KPK dari kedua penyebut supaya angka-angkanya tidak terlalu besar.",
  "Untuk menyamakan penyebut, kalikan pembilang dan penyebut dengan bilangan yang sama.",
  "Jangan langsung membandingkan pembilang kalau penyebutnya berbeda. 1/3 dan 2/5 harus disamakan dulu!",
  "Menggambar dua batang cokelat yang sama besar bisa membantumu membandingkan dua pecahan.",
  "Pecahan 1/2 bisa jadi patokan: pecahan yang lebih besar dari 1/2 berarti lebih dari setengah.",
  "Dua pecahan bisa terlihat berbeda tetapi nilainya sama, seperti 1/2 dan 3/6.",
  "Setelah membandingkan, periksa lagi arah simbol > atau < yang kamu tulis.",

  // ── Mengurutkan pecahan ──
  "Mengurutkan pecahan dari yang terkecil ke terbesar disebut urutan naik.",
  "Mengurutkan pecahan dari yang terbesar ke terkecil disebut urutan turun.",
  "Sebelum mengurutkan, baca soal dengan teliti: diminta dari yang terkecil atau dari yang terbesar?",
  "Jika penyebutnya sama, urutkan pecahan dengan melihat pembilangnya saja.",
  "Untuk mengurutkan pecahan berpenyebut berbeda, samakan semua penyebutnya dengan KPK terlebih dahulu.",
  "Setelah mengurutkan pecahan yang penyebutnya sudah disamakan, jangan lupa tulis kembali bentuk pecahan aslinya.",
  "Jika beberapa pecahan pembilangnya sama, urutkan lewat penyebutnya: penyebut lebih kecil berarti pecahan lebih besar.",
  "Urutan 1/2, 1/3, dan 1/4 dari yang terkecil adalah 1/4, 1/3, 1/2.",
  "Membandingkan dua pecahan dulu bisa membantumu mengurutkan tiga pecahan atau lebih.",
  "Setelah mengurutkan, cek lagi dengan membandingkan pecahan yang bersebelahan.",

  // ── Penjumlahan pecahan ──
  "Jika penyebutnya sama, jumlahkan pembilangnya saja dan penyebutnya tetap.",
  "Penyebut tidak ikut dijumlahkan. 2/7 + 3/7 = 5/7, bukan 5/14.",
  "Menjumlahkan pecahan itu seperti menggabungkan potongan kue yang sama besar.",
  "Hasil penjumlahan dua pecahan bisa lebih dari 1. Contohnya, 4/5 + 3/5 = 7/5.",
  "Pecahan 7/5 bisa ditulis 1 2/5, artinya satu utuh ditambah dua per lima.",
  "Pecahan berpenyebut berbeda tidak bisa langsung dijumlahkan. Samakan dulu penyebutnya.",
  "Langkah menjumlahkan pecahan berpenyebut berbeda: cari KPK, samakan penyebut, lalu jumlahkan pembilangnya.",
  "1/3 + 1/4 bukan 2/7. Samakan penyebutnya menjadi 4/12 + 3/12 = 7/12.",
  "Urutan penjumlahan boleh dibolak-balik. 1/4 + 2/4 sama dengan 2/4 + 1/4.",
  'Kata "total", "seluruhnya", dan "gabungan" dalam soal cerita biasanya berarti penjumlahan.',
  "Saat menyamakan penyebut, ubah pecahannya, bukan hanya penyebutnya. Pembilang juga harus dikalikan!",
  "Jika penyebut yang satu kelipatan penyebut yang lain, KPK-nya adalah penyebut yang lebih besar. Contohnya 1/2 + 1/4, KPK-nya 4.",
  "Setelah menjumlahkan, periksa apakah hasilnya masuk akal. 1/2 + 1/4 tidak mungkin kurang dari 1/2.",

  // ── Pengurangan pecahan ──
  "Jika penyebutnya sama, kurangkan pembilangnya saja dan penyebutnya tetap.",
  "5/9 − 2/9 = 3/9. Penyebutnya tidak ikut dikurangkan!",
  "Kalau penyebut ikut dikurangkan, hasilnya bisa menjadi 0. Padahal penyebut tidak boleh 0!",
  "Pecahan berpenyebut berbeda harus disamakan penyebutnya dulu sebelum dikurangkan.",
  "Langkah pengurangan pecahan berpenyebut berbeda sama dengan penjumlahan: cari KPK, samakan penyebut, lalu kurangkan pembilangnya.",
  "3/4 − 1/3 = 9/12 − 4/12 = 5/12.",
  'Kata "sisa", "selisih", dan "tinggal" dalam soal cerita biasanya berarti pengurangan.',
  "Berbeda dengan penjumlahan, urutan pengurangan tidak boleh dibalik.",
  "Penjumlahan dan pengurangan saling berkebalikan. Jika 2/5 + 1/5 = 3/5, maka 3/5 − 1/5 = 2/5.",
  "Bayangkan pengurangan pecahan seperti memakan sebagian kue yang kamu punya.",

  // ── Tips belajar dan semangat ──
  "Berlatih sedikit setiap hari lebih baik daripada belajar lama sekali dalam sehari.",
  "Salah itu tidak apa-apa! Dari kesalahan, kita belajar cara yang benar.",
  "Kalau soal terasa sulit, coba gambar dulu. Gambar sering membuat soal lebih mudah dipahami.",
  "Baca soal cerita pelan-pelan dan garis bawahi angka-angka pentingnya.",
  "Tanyakan pada dirimu: apa yang diketahui dan apa yang ditanyakan dalam soal?",
  "Jangan terburu-buru. Mengerjakan dengan teliti lebih penting daripada cepat.",
  "Setelah selesai mengerjakan soal, periksa kembali jawabanmu.",
  "Menjelaskan cara menjawab kepada temanmu bisa membuatmu semakin paham.",
  "Hafalkan perkalian dasar. Itu sangat membantu saat mencari KPK dan menyamakan penyebut.",
  "Cara mencari KPK: tulis kelipatan kedua bilangan sampai ketemu angka yang sama. Kelipatan 3: 3, 6, 9, 12. Kelipatan 4: 4, 8, 12. KPK-nya 12!",
  "Hasil seperti 4/8 sama nilainya dengan 1/2, jadi keduanya adalah jawaban yang benar.",
  "Gunakan benda di sekitarmu, seperti kancing atau kertas lipat, untuk memahami pecahan.",
  "Melipat kertas menjadi dua, empat, atau delapan bagian adalah cara seru untuk melihat pecahan.",
  "Jangan menyerah kalau jawabanmu salah. Coba lagi dengan cara yang berbeda.",
  "Istirahat sebentar bisa membuat otakmu segar kembali.",
  "Manfaatkan petunjuk (hint) sebagai bantuan untuk berpikir, bukan alasan untuk menyerah.",
  "Menulis langkah pengerjaan satu per satu membuatmu lebih mudah menemukan kesalahan.",
  "Setiap kali kamu berhasil menjawab, otakmu jadi makin kuat, seperti otot yang terus dilatih.",
  "Pecahan akan sering kamu temui saat memasak, berbelanja, dan membagi makanan.",
  "Kamu hebat sudah sampai sejauh ini! Terus semangat belajar pecahan.",
];
