// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit

import type {
	Contract as ContractType,
	ExecutionHashBase,
	NamespaceId,
	ProfileHashBase,
	StorageHashBase,
} from '@prisma/orm-postgres/contract/types';
import type {
	ContractWithTypeMaps,
	RelationKeys,
	TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
	Bit,
	Char,
	Interval,
	JsonValue,
	Numeric,
	CodecTypes as PgTypes,
	Time,
	TimeString,
	Timestamp,
	TimestampString,
	Timestamptz,
	TimestamptzString,
	Timetz,
	VarBit,
	Varchar,
} from '@prisma/orm-postgres/target/codec-types';
import type { QueryOperationTypes as PgTargetQueryOps } from '@prisma/orm-postgres/target/operation-types';

export type StorageHash =
	StorageHashBase<'21d4303f0b0d6b6a7b4dc76ecaa41e4ff0b40f311443926b93c18e22dd879ea1'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
	ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
	readonly avg: {
		readonly byCodec: {
			readonly 'pg/float@1': {
				readonly output: 'pg/float8@1';
				readonly nullable: true;
			};
			readonly 'pg/float4@1': {
				readonly output: 'pg/float8@1';
				readonly nullable: true;
			};
			readonly 'pg/float8@1': {
				readonly output: 'pg/float8@1';
				readonly nullable: true;
			};
			readonly 'pg/int@1': {
				readonly output: 'pg/float8@1';
				readonly nullable: true;
			};
			readonly 'pg/int2@1': {
				readonly output: 'pg/float8@1';
				readonly nullable: true;
			};
			readonly 'pg/int4@1': {
				readonly output: 'pg/float8@1';
				readonly nullable: true;
			};
			readonly 'pg/int8@1': {
				readonly output: 'pg/float8@1';
				readonly nullable: true;
			};
			readonly 'pg/int8number@1': {
				readonly output: 'pg/float8@1';
				readonly nullable: true;
			};
			readonly 'pg/interval@1': {
				readonly output: 'pg/interval@1';
				readonly nullable: true;
			};
			readonly 'pg/numeric@1': {
				readonly output: 'pg/numeric@1';
				readonly nullable: true;
			};
			readonly 'pg/time-string@1': {
				readonly output: 'pg/interval@1';
				readonly nullable: true;
			};
			readonly 'pg/time-temporal@1': {
				readonly output: 'pg/interval@1';
				readonly nullable: true;
			};
			readonly 'pg/unboundedint@1': {
				readonly output: 'pg/float8@1';
				readonly nullable: true;
			};
			readonly 'sql/float@1': {
				readonly output: 'pg/float8@1';
				readonly nullable: true;
			};
			readonly 'sql/int@1': {
				readonly output: 'pg/float8@1';
				readonly nullable: true;
			};
		};
	};
	readonly avgDecimal: {
		readonly byCodec: {
			readonly 'pg/int@1': {
				readonly output: 'pg/numeric@1';
				readonly nullable: true;
			};
			readonly 'pg/int2@1': {
				readonly output: 'pg/numeric@1';
				readonly nullable: true;
			};
			readonly 'pg/int4@1': {
				readonly output: 'pg/numeric@1';
				readonly nullable: true;
			};
			readonly 'pg/int8@1': {
				readonly output: 'pg/numeric@1';
				readonly nullable: true;
			};
			readonly 'pg/int8number@1': {
				readonly output: 'pg/numeric@1';
				readonly nullable: true;
			};
			readonly 'pg/numeric@1': {
				readonly output: 'pg/numeric@1';
				readonly nullable: true;
			};
			readonly 'pg/unboundedint@1': {
				readonly output: 'pg/numeric@1';
				readonly nullable: true;
			};
			readonly 'sql/int@1': {
				readonly output: 'pg/numeric@1';
				readonly nullable: true;
			};
		};
	};
	readonly count: {
		readonly byCodec: {};
		readonly withoutInput: {
			readonly output: 'pg/int8number@1';
			readonly nullable: false;
		};
		readonly anyInput: {
			readonly output: 'pg/int8number@1';
			readonly nullable: false;
		};
	};
	readonly countBigInt: {
		readonly byCodec: {};
		readonly withoutInput: {
			readonly output: 'pg/int8@1';
			readonly nullable: false;
		};
		readonly anyInput: {
			readonly output: 'pg/int8@1';
			readonly nullable: false;
		};
	};
	readonly max: {
		readonly byCodec: {
			readonly 'pg/char@1': {
				readonly output: 'pg/char@1';
				readonly nullable: true;
			};
			readonly 'pg/date-string@1': {
				readonly output: 'pg/date-string@1';
				readonly nullable: true;
			};
			readonly 'pg/date-temporal@1': {
				readonly output: 'pg/date-temporal@1';
				readonly nullable: true;
			};
			readonly 'pg/enum@1': {
				readonly output: 'pg/enum@1';
				readonly nullable: true;
			};
			readonly 'pg/float@1': {
				readonly output: 'pg/float@1';
				readonly nullable: true;
			};
			readonly 'pg/float4@1': {
				readonly output: 'pg/float4@1';
				readonly nullable: true;
			};
			readonly 'pg/float8@1': {
				readonly output: 'pg/float8@1';
				readonly nullable: true;
			};
			readonly 'pg/inet@1': {
				readonly output: 'pg/inet@1';
				readonly nullable: true;
			};
			readonly 'pg/int@1': {
				readonly output: 'pg/int@1';
				readonly nullable: true;
			};
			readonly 'pg/int2@1': {
				readonly output: 'pg/int2@1';
				readonly nullable: true;
			};
			readonly 'pg/int4@1': {
				readonly output: 'pg/int4@1';
				readonly nullable: true;
			};
			readonly 'pg/int8@1': {
				readonly output: 'pg/int8@1';
				readonly nullable: true;
			};
			readonly 'pg/int8number@1': {
				readonly output: 'pg/int8number@1';
				readonly nullable: true;
			};
			readonly 'pg/interval@1': {
				readonly output: 'pg/interval@1';
				readonly nullable: true;
			};
			readonly 'pg/numeric@1': {
				readonly output: 'pg/numeric@1';
				readonly nullable: true;
			};
			readonly 'pg/text-array@1': {
				readonly output: 'pg/text-array@1';
				readonly nullable: true;
			};
			readonly 'pg/text@1': {
				readonly output: 'pg/text@1';
				readonly nullable: true;
			};
			readonly 'pg/time-string@1': {
				readonly output: 'pg/time-string@1';
				readonly nullable: true;
			};
			readonly 'pg/time-temporal@1': {
				readonly output: 'pg/time-temporal@1';
				readonly nullable: true;
			};
			readonly 'pg/timestamp-string@1': {
				readonly output: 'pg/timestamp-string@1';
				readonly nullable: true;
			};
			readonly 'pg/timestamp-temporal@1': {
				readonly output: 'pg/timestamp-temporal@1';
				readonly nullable: true;
			};
			readonly 'pg/timestamptz-date@1': {
				readonly output: 'pg/timestamptz-date@1';
				readonly nullable: true;
			};
			readonly 'pg/timestamptz-string@1': {
				readonly output: 'pg/timestamptz-string@1';
				readonly nullable: true;
			};
			readonly 'pg/timestamptz-temporal@1': {
				readonly output: 'pg/timestamptz-temporal@1';
				readonly nullable: true;
			};
			readonly 'pg/timetz@1': {
				readonly output: 'pg/timetz@1';
				readonly nullable: true;
			};
			readonly 'pg/unboundedint@1': {
				readonly output: 'pg/unboundedint@1';
				readonly nullable: true;
			};
			readonly 'pg/varchar@1': {
				readonly output: 'pg/text@1';
				readonly nullable: true;
			};
			readonly 'sql/char@1': {
				readonly output: 'sql/char@1';
				readonly nullable: true;
			};
			readonly 'sql/float@1': {
				readonly output: 'sql/float@1';
				readonly nullable: true;
			};
			readonly 'sql/int@1': {
				readonly output: 'sql/int@1';
				readonly nullable: true;
			};
			readonly 'sql/text@1': {
				readonly output: 'sql/text@1';
				readonly nullable: true;
			};
			readonly 'sql/varchar@1': {
				readonly output: 'pg/text@1';
				readonly nullable: true;
			};
		};
	};
	readonly min: {
		readonly byCodec: {
			readonly 'pg/char@1': {
				readonly output: 'pg/char@1';
				readonly nullable: true;
			};
			readonly 'pg/date-string@1': {
				readonly output: 'pg/date-string@1';
				readonly nullable: true;
			};
			readonly 'pg/date-temporal@1': {
				readonly output: 'pg/date-temporal@1';
				readonly nullable: true;
			};
			readonly 'pg/enum@1': {
				readonly output: 'pg/enum@1';
				readonly nullable: true;
			};
			readonly 'pg/float@1': {
				readonly output: 'pg/float@1';
				readonly nullable: true;
			};
			readonly 'pg/float4@1': {
				readonly output: 'pg/float4@1';
				readonly nullable: true;
			};
			readonly 'pg/float8@1': {
				readonly output: 'pg/float8@1';
				readonly nullable: true;
			};
			readonly 'pg/inet@1': {
				readonly output: 'pg/inet@1';
				readonly nullable: true;
			};
			readonly 'pg/int@1': {
				readonly output: 'pg/int@1';
				readonly nullable: true;
			};
			readonly 'pg/int2@1': {
				readonly output: 'pg/int2@1';
				readonly nullable: true;
			};
			readonly 'pg/int4@1': {
				readonly output: 'pg/int4@1';
				readonly nullable: true;
			};
			readonly 'pg/int8@1': {
				readonly output: 'pg/int8@1';
				readonly nullable: true;
			};
			readonly 'pg/int8number@1': {
				readonly output: 'pg/int8number@1';
				readonly nullable: true;
			};
			readonly 'pg/interval@1': {
				readonly output: 'pg/interval@1';
				readonly nullable: true;
			};
			readonly 'pg/numeric@1': {
				readonly output: 'pg/numeric@1';
				readonly nullable: true;
			};
			readonly 'pg/text-array@1': {
				readonly output: 'pg/text-array@1';
				readonly nullable: true;
			};
			readonly 'pg/text@1': {
				readonly output: 'pg/text@1';
				readonly nullable: true;
			};
			readonly 'pg/time-string@1': {
				readonly output: 'pg/time-string@1';
				readonly nullable: true;
			};
			readonly 'pg/time-temporal@1': {
				readonly output: 'pg/time-temporal@1';
				readonly nullable: true;
			};
			readonly 'pg/timestamp-string@1': {
				readonly output: 'pg/timestamp-string@1';
				readonly nullable: true;
			};
			readonly 'pg/timestamp-temporal@1': {
				readonly output: 'pg/timestamp-temporal@1';
				readonly nullable: true;
			};
			readonly 'pg/timestamptz-date@1': {
				readonly output: 'pg/timestamptz-date@1';
				readonly nullable: true;
			};
			readonly 'pg/timestamptz-string@1': {
				readonly output: 'pg/timestamptz-string@1';
				readonly nullable: true;
			};
			readonly 'pg/timestamptz-temporal@1': {
				readonly output: 'pg/timestamptz-temporal@1';
				readonly nullable: true;
			};
			readonly 'pg/timetz@1': {
				readonly output: 'pg/timetz@1';
				readonly nullable: true;
			};
			readonly 'pg/unboundedint@1': {
				readonly output: 'pg/unboundedint@1';
				readonly nullable: true;
			};
			readonly 'pg/varchar@1': {
				readonly output: 'pg/text@1';
				readonly nullable: true;
			};
			readonly 'sql/char@1': {
				readonly output: 'sql/char@1';
				readonly nullable: true;
			};
			readonly 'sql/float@1': {
				readonly output: 'sql/float@1';
				readonly nullable: true;
			};
			readonly 'sql/int@1': {
				readonly output: 'sql/int@1';
				readonly nullable: true;
			};
			readonly 'sql/text@1': {
				readonly output: 'sql/text@1';
				readonly nullable: true;
			};
			readonly 'sql/varchar@1': {
				readonly output: 'pg/text@1';
				readonly nullable: true;
			};
		};
	};
	readonly sum: {
		readonly byCodec: {
			readonly 'pg/float@1': {
				readonly output: 'pg/float8@1';
				readonly nullable: true;
			};
			readonly 'pg/float4@1': {
				readonly output: 'pg/float4@1';
				readonly nullable: true;
			};
			readonly 'pg/float8@1': {
				readonly output: 'pg/float8@1';
				readonly nullable: true;
			};
			readonly 'pg/int@1': {
				readonly output: 'pg/int8number@1';
				readonly nullable: true;
			};
			readonly 'pg/int2@1': {
				readonly output: 'pg/int8number@1';
				readonly nullable: true;
			};
			readonly 'pg/int4@1': {
				readonly output: 'pg/int8number@1';
				readonly nullable: true;
			};
			readonly 'pg/int8@1': {
				readonly output: 'pg/int8number@1';
				readonly nullable: true;
			};
			readonly 'pg/int8number@1': {
				readonly output: 'pg/int8number@1';
				readonly nullable: true;
			};
			readonly 'pg/interval@1': {
				readonly output: 'pg/interval@1';
				readonly nullable: true;
			};
			readonly 'pg/numeric@1': {
				readonly output: 'pg/numeric@1';
				readonly nullable: true;
			};
			readonly 'pg/time-string@1': {
				readonly output: 'pg/interval@1';
				readonly nullable: true;
			};
			readonly 'pg/time-temporal@1': {
				readonly output: 'pg/interval@1';
				readonly nullable: true;
			};
			readonly 'pg/unboundedint@1': {
				readonly output: 'pg/unboundedint@1';
				readonly nullable: true;
			};
			readonly 'sql/float@1': {
				readonly output: 'pg/float8@1';
				readonly nullable: true;
			};
			readonly 'sql/int@1': {
				readonly output: 'pg/int8number@1';
				readonly nullable: true;
			};
		};
	};
	readonly sumBigInt: {
		readonly byCodec: {
			readonly 'pg/int@1': {
				readonly output: 'pg/int8@1';
				readonly nullable: true;
			};
			readonly 'pg/int2@1': {
				readonly output: 'pg/int8@1';
				readonly nullable: true;
			};
			readonly 'pg/int4@1': {
				readonly output: 'pg/int8@1';
				readonly nullable: true;
			};
			readonly 'pg/int8@1': {
				readonly output: 'pg/unboundedint@1';
				readonly nullable: true;
			};
			readonly 'pg/int8number@1': {
				readonly output: 'pg/unboundedint@1';
				readonly nullable: true;
			};
			readonly 'pg/unboundedint@1': {
				readonly output: 'pg/unboundedint@1';
				readonly nullable: true;
			};
			readonly 'sql/int@1': {
				readonly output: 'pg/int8@1';
				readonly nullable: true;
			};
		};
	};
};
type DefaultLiteralValue<
	CodecId extends string,
	Encoded,
> = CodecId extends keyof CodecTypes
	? Encoded extends CodecTypes[CodecId]['json']
		? Encoded
		: CodecTypes[CodecId]['json']
	: Encoded;

export type FieldOutputTypes = {
	readonly public: {
		readonly User: {
			readonly grade: CodecTypes['pg/int4@1']['output'] | null;
			readonly id: CodecTypes['pg/int4@1']['output'];
			readonly isAdmin: CodecTypes['pg/bool@1']['output'];
			readonly name: CodecTypes['pg/text@1']['output'];
			readonly password: CodecTypes['pg/text@1']['output'];
			readonly username: CodecTypes['pg/text@1']['output'];
		};
	};
};
export type FieldInputTypes = {
	readonly public: {
		readonly User: {
			readonly grade: CodecTypes['pg/int4@1']['input'] | null;
			readonly id: CodecTypes['pg/int4@1']['input'];
			readonly isAdmin: CodecTypes['pg/bool@1']['input'];
			readonly name: CodecTypes['pg/text@1']['input'];
			readonly password: CodecTypes['pg/text@1']['input'];
			readonly username: CodecTypes['pg/text@1']['input'];
		};
	};
};
export type StorageColumnTypes = {
	readonly public: {
		readonly User: {
			readonly grade: CodecTypes['pg/int4@1']['output'] | null;
			readonly id: CodecTypes['pg/int4@1']['output'];
			readonly isAdmin: CodecTypes['pg/bool@1']['output'];
			readonly name: CodecTypes['pg/text@1']['output'];
			readonly password: CodecTypes['pg/text@1']['output'];
			readonly username: CodecTypes['pg/text@1']['output'];
		};
	};
};
export type StorageColumnInputTypes = {
	readonly public: {
		readonly User: {
			readonly grade: CodecTypes['pg/int4@1']['input'] | null;
			readonly id: CodecTypes['pg/int4@1']['input'];
			readonly isAdmin: CodecTypes['pg/bool@1']['input'];
			readonly name: CodecTypes['pg/text@1']['input'];
			readonly password: CodecTypes['pg/text@1']['input'];
			readonly username: CodecTypes['pg/text@1']['input'];
		};
	};
};

export namespace Models {
	export type public_User = {
		grade: CodecTypes['pg/int4@1']['output'] | null;
		id: CodecTypes['pg/int4@1']['output'];
		isAdmin: CodecTypes['pg/bool@1']['output'];
		name: CodecTypes['pg/text@1']['output'];
		password: CodecTypes['pg/text@1']['output'];
		username: CodecTypes['pg/text@1']['output'];
		readonly [RelationKeys]?: never;
	};
}

export declare const models: {
	public: {
		User: Models.public_User;
	};
};

export type TypeMaps = TypeMapsType<
	CodecTypes,
	QueryOperationTypes,
	FieldOutputTypes,
	FieldInputTypes,
	StorageColumnTypes,
	StorageColumnInputTypes,
	AggregateTypes
>;

type ContractBase = Omit<
	ContractType<{
		readonly namespaces: {
			readonly public: {
				readonly id: 'public';
				readonly kind: 'postgres-schema';
				readonly entries: {
					readonly table: {
						readonly User: {
							columns: {
								readonly grade: {
									readonly nativeType: 'int4';
									readonly codecId: 'pg/int4@1';
									readonly nullable: true;
								};
								readonly id: {
									readonly nativeType: 'int4';
									readonly codecId: 'pg/int4@1';
									readonly nullable: false;
									readonly default: {
										readonly kind: 'function';
										readonly expression: 'autoincrement()';
									};
								};
								readonly isAdmin: {
									readonly nativeType: 'bool';
									readonly codecId: 'pg/bool@1';
									readonly nullable: false;
									readonly default: {
										readonly kind: 'literal';
										readonly value: DefaultLiteralValue<
											'pg/bool@1',
											false
										>;
									};
								};
								readonly name: {
									readonly nativeType: 'text';
									readonly codecId: 'pg/text@1';
									readonly nullable: false;
								};
								readonly password: {
									readonly nativeType: 'text';
									readonly codecId: 'pg/text@1';
									readonly nullable: false;
								};
								readonly username: {
									readonly nativeType: 'text';
									readonly codecId: 'pg/text@1';
									readonly nullable: false;
								};
							};
							primaryKey: { readonly columns: readonly ['id'] };
							uniques: readonly [
								{ readonly columns: readonly ['username'] },
							];
							indexes: readonly [];
							foreignKeys: readonly [];
						};
					};
				};
			};
		};
		readonly storageHash: StorageHash;
	}>,
	'roots' | 'domain'
> & {
	readonly target: 'postgres';
	readonly targetFamily: 'sql';
	readonly roots: {
		readonly User: {
			readonly namespace: 'public' & NamespaceId;
			readonly model: 'User';
		};
	};
	readonly domain: {
		readonly namespaces: {
			readonly public: {
				readonly models: {
					readonly User: {
						readonly fields: {
							readonly grade: {
								readonly nullable: true;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/int4@1';
								};
							};
							readonly id: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/int4@1';
								};
							};
							readonly isAdmin: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/bool@1';
								};
							};
							readonly name: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/text@1';
								};
							};
							readonly password: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/text@1';
								};
							};
							readonly username: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/text@1';
								};
							};
						};
						readonly relations: Record<string, never>;
						readonly storage: {
							readonly table: 'User';
							readonly namespaceId: 'public';
							readonly fields: {
								readonly grade: { readonly column: 'grade' };
								readonly id: { readonly column: 'id' };
								readonly isAdmin: {
									readonly column: 'isAdmin';
								};
								readonly name: { readonly column: 'name' };
								readonly password: {
									readonly column: 'password';
								};
								readonly username: {
									readonly column: 'username';
								};
							};
						};
					};
				};
			};
		};
	};
	readonly capabilities: {
		readonly postgres: {
			readonly distinctOn: true;
			readonly jsonAgg: true;
			readonly lateral: true;
			readonly limit: true;
			readonly orderBy: true;
			readonly returning: true;
		};
		readonly sql: {
			readonly checkConstraint: true;
			readonly defaultInInsert: true;
			readonly enums: true;
			readonly insertOnConflictSkip: true;
			readonly insertOnConflictWithoutTarget: true;
			readonly lateral: true;
			readonly returning: true;
			readonly scalarList: true;
		};
	};
	readonly extensions: {};
	readonly meta: {};

	readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
