// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit

import type {
	Contract as ContractType,
	ExecutionHashBase,
	NamespaceId,
	ProfileHashBase,
	StorageHashBase,
} from '@prisma/orm-postgres/contract/types';
import type {
	ContractWithTypeMaps,
	RelationKeys,
	TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
	Bit,
	Char,
	Interval,
	JsonValue,
	Numeric,
	CodecTypes as PgTypes,
	Time,
	TimeString,
	Timestamp,
	TimestampString,
	Timestamptz,
	TimestamptzString,
	Timetz,
	VarBit,
	Varchar,
} from '@prisma/orm-postgres/target/codec-types';
import type { QueryOperationTypes as PgTargetQueryOps } from '@prisma/orm-postgres/target/operation-types';

export type StorageHash =
	StorageHashBase<'8c5140a7175bf1fd61dd18cddcd60e9c00dd28ec2eba01ab0996f659d733be54'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
	ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
	readonly avg: {
		readonly byCodec: {
			readonly 'pg/float@1': {
				readonly output: 'pg/float8@1';
				readonly nullable: true;
			};
			readonly 'pg/float4@1': {
				readonly output: 'pg/float8@1';
				readonly nullable: true;
			};
			readonly 'pg/float8@1': {
				readonly output: 'pg/float8@1';
				readonly nullable: true;
			};
			readonly 'pg/int@1': {
				readonly output: 'pg/float8@1';
				readonly nullable: true;
			};
			readonly 'pg/int2@1': {
				readonly output: 'pg/float8@1';
				readonly nullable: true;
			};
			readonly 'pg/int4@1': {
				readonly output: 'pg/float8@1';
				readonly nullable: true;
			};
			readonly 'pg/int8@1': {
				readonly output: 'pg/float8@1';
				readonly nullable: true;
			};
			readonly 'pg/int8number@1': {
				readonly output: 'pg/float8@1';
				readonly nullable: true;
			};
			readonly 'pg/interval@1': {
				readonly output: 'pg/interval@1';
				readonly nullable: true;
			};
			readonly 'pg/numeric@1': {
				readonly output: 'pg/numeric@1';
				readonly nullable: true;
			};
			readonly 'pg/time-string@1': {
				readonly output: 'pg/interval@1';
				readonly nullable: true;
			};
			readonly 'pg/time-temporal@1': {
				readonly output: 'pg/interval@1';
				readonly nullable: true;
			};
			readonly 'pg/unboundedint@1': {
				readonly output: 'pg/float8@1';
				readonly nullable: true;
			};
			readonly 'sql/float@1': {
				readonly output: 'pg/float8@1';
				readonly nullable: true;
			};
			readonly 'sql/int@1': {
				readonly output: 'pg/float8@1';
				readonly nullable: true;
			};
		};
	};
	readonly avgDecimal: {
		readonly byCodec: {
			readonly 'pg/int@1': {
				readonly output: 'pg/numeric@1';
				readonly nullable: true;
			};
			readonly 'pg/int2@1': {
				readonly output: 'pg/numeric@1';
				readonly nullable: true;
			};
			readonly 'pg/int4@1': {
				readonly output: 'pg/numeric@1';
				readonly nullable: true;
			};
			readonly 'pg/int8@1': {
				readonly output: 'pg/numeric@1';
				readonly nullable: true;
			};
			readonly 'pg/int8number@1': {
				readonly output: 'pg/numeric@1';
				readonly nullable: true;
			};
			readonly 'pg/numeric@1': {
				readonly output: 'pg/numeric@1';
				readonly nullable: true;
			};
			readonly 'pg/unboundedint@1': {
				readonly output: 'pg/numeric@1';
				readonly nullable: true;
			};
			readonly 'sql/int@1': {
				readonly output: 'pg/numeric@1';
				readonly nullable: true;
			};
		};
	};
	readonly count: {
		readonly byCodec: {};
		readonly withoutInput: {
			readonly output: 'pg/int8number@1';
			readonly nullable: false;
		};
		readonly anyInput: {
			readonly output: 'pg/int8number@1';
			readonly nullable: false;
		};
	};
	readonly countBigInt: {
		readonly byCodec: {};
		readonly withoutInput: {
			readonly output: 'pg/int8@1';
			readonly nullable: false;
		};
		readonly anyInput: {
			readonly output: 'pg/int8@1';
			readonly nullable: false;
		};
	};
	readonly max: {
		readonly byCodec: {
			readonly 'pg/char@1': {
				readonly output: 'pg/char@1';
				readonly nullable: true;
			};
			readonly 'pg/date-string@1': {
				readonly output: 'pg/date-string@1';
				readonly nullable: true;
			};
			readonly 'pg/date-temporal@1': {
				readonly output: 'pg/date-temporal@1';
				readonly nullable: true;
			};
			readonly 'pg/enum@1': {
				readonly output: 'pg/enum@1';
				readonly nullable: true;
			};
			readonly 'pg/float@1': {
				readonly output: 'pg/float@1';
				readonly nullable: true;
			};
			readonly 'pg/float4@1': {
				readonly output: 'pg/float4@1';
				readonly nullable: true;
			};
			readonly 'pg/float8@1': {
				readonly output: 'pg/float8@1';
				readonly nullable: true;
			};
			readonly 'pg/inet@1': {
				readonly output: 'pg/inet@1';
				readonly nullable: true;
			};
			readonly 'pg/int@1': {
				readonly output: 'pg/int@1';
				readonly nullable: true;
			};
			readonly 'pg/int2@1': {
				readonly output: 'pg/int2@1';
				readonly nullable: true;
			};
			readonly 'pg/int4@1': {
				readonly output: 'pg/int4@1';
				readonly nullable: true;
			};
			readonly 'pg/int8@1': {
				readonly output: 'pg/int8@1';
				readonly nullable: true;
			};
			readonly 'pg/int8number@1': {
				readonly output: 'pg/int8number@1';
				readonly nullable: true;
			};
			readonly 'pg/interval@1': {
				readonly output: 'pg/interval@1';
				readonly nullable: true;
			};
			readonly 'pg/numeric@1': {
				readonly output: 'pg/numeric@1';
				readonly nullable: true;
			};
			readonly 'pg/text-array@1': {
				readonly output: 'pg/text-array@1';
				readonly nullable: true;
			};
			readonly 'pg/text@1': {
				readonly output: 'pg/text@1';
				readonly nullable: true;
			};
			readonly 'pg/time-string@1': {
				readonly output: 'pg/time-string@1';
				readonly nullable: true;
			};
			readonly 'pg/time-temporal@1': {
				readonly output: 'pg/time-temporal@1';
				readonly nullable: true;
			};
			readonly 'pg/timestamp-string@1': {
				readonly output: 'pg/timestamp-string@1';
				readonly nullable: true;
			};
			readonly 'pg/timestamp-temporal@1': {
				readonly output: 'pg/timestamp-temporal@1';
				readonly nullable: true;
			};
			readonly 'pg/timestamptz-date@1': {
				readonly output: 'pg/timestamptz-date@1';
				readonly nullable: true;
			};
			readonly 'pg/timestamptz-string@1': {
				readonly output: 'pg/timestamptz-string@1';
				readonly nullable: true;
			};
			readonly 'pg/timestamptz-temporal@1': {
				readonly output: 'pg/timestamptz-temporal@1';
				readonly nullable: true;
			};
			readonly 'pg/timetz@1': {
				readonly output: 'pg/timetz@1';
				readonly nullable: true;
			};
			readonly 'pg/unboundedint@1': {
				readonly output: 'pg/unboundedint@1';
				readonly nullable: true;
			};
			readonly 'pg/varchar@1': {
				readonly output: 'pg/text@1';
				readonly nullable: true;
			};
			readonly 'sql/char@1': {
				readonly output: 'sql/char@1';
				readonly nullable: true;
			};
			readonly 'sql/float@1': {
				readonly output: 'sql/float@1';
				readonly nullable: true;
			};
			readonly 'sql/int@1': {
				readonly output: 'sql/int@1';
				readonly nullable: true;
			};
			readonly 'sql/text@1': {
				readonly output: 'sql/text@1';
				readonly nullable: true;
			};
			readonly 'sql/varchar@1': {
				readonly output: 'pg/text@1';
				readonly nullable: true;
			};
		};
	};
	readonly min: {
		readonly byCodec: {
			readonly 'pg/char@1': {
				readonly output: 'pg/char@1';
				readonly nullable: true;
			};
			readonly 'pg/date-string@1': {
				readonly output: 'pg/date-string@1';
				readonly nullable: true;
			};
			readonly 'pg/date-temporal@1': {
				readonly output: 'pg/date-temporal@1';
				readonly nullable: true;
			};
			readonly 'pg/enum@1': {
				readonly output: 'pg/enum@1';
				readonly nullable: true;
			};
			readonly 'pg/float@1': {
				readonly output: 'pg/float@1';
				readonly nullable: true;
			};
			readonly 'pg/float4@1': {
				readonly output: 'pg/float4@1';
				readonly nullable: true;
			};
			readonly 'pg/float8@1': {
				readonly output: 'pg/float8@1';
				readonly nullable: true;
			};
			readonly 'pg/inet@1': {
				readonly output: 'pg/inet@1';
				readonly nullable: true;
			};
			readonly 'pg/int@1': {
				readonly output: 'pg/int@1';
				readonly nullable: true;
			};
			readonly 'pg/int2@1': {
				readonly output: 'pg/int2@1';
				readonly nullable: true;
			};
			readonly 'pg/int4@1': {
				readonly output: 'pg/int4@1';
				readonly nullable: true;
			};
			readonly 'pg/int8@1': {
				readonly output: 'pg/int8@1';
				readonly nullable: true;
			};
			readonly 'pg/int8number@1': {
				readonly output: 'pg/int8number@1';
				readonly nullable: true;
			};
			readonly 'pg/interval@1': {
				readonly output: 'pg/interval@1';
				readonly nullable: true;
			};
			readonly 'pg/numeric@1': {
				readonly output: 'pg/numeric@1';
				readonly nullable: true;
			};
			readonly 'pg/text-array@1': {
				readonly output: 'pg/text-array@1';
				readonly nullable: true;
			};
			readonly 'pg/text@1': {
				readonly output: 'pg/text@1';
				readonly nullable: true;
			};
			readonly 'pg/time-string@1': {
				readonly output: 'pg/time-string@1';
				readonly nullable: true;
			};
			readonly 'pg/time-temporal@1': {
				readonly output: 'pg/time-temporal@1';
				readonly nullable: true;
			};
			readonly 'pg/timestamp-string@1': {
				readonly output: 'pg/timestamp-string@1';
				readonly nullable: true;
			};
			readonly 'pg/timestamp-temporal@1': {
				readonly output: 'pg/timestamp-temporal@1';
				readonly nullable: true;
			};
			readonly 'pg/timestamptz-date@1': {
				readonly output: 'pg/timestamptz-date@1';
				readonly nullable: true;
			};
			readonly 'pg/timestamptz-string@1': {
				readonly output: 'pg/timestamptz-string@1';
				readonly nullable: true;
			};
			readonly 'pg/timestamptz-temporal@1': {
				readonly output: 'pg/timestamptz-temporal@1';
				readonly nullable: true;
			};
			readonly 'pg/timetz@1': {
				readonly output: 'pg/timetz@1';
				readonly nullable: true;
			};
			readonly 'pg/unboundedint@1': {
				readonly output: 'pg/unboundedint@1';
				readonly nullable: true;
			};
			readonly 'pg/varchar@1': {
				readonly output: 'pg/text@1';
				readonly nullable: true;
			};
			readonly 'sql/char@1': {
				readonly output: 'sql/char@1';
				readonly nullable: true;
			};
			readonly 'sql/float@1': {
				readonly output: 'sql/float@1';
				readonly nullable: true;
			};
			readonly 'sql/int@1': {
				readonly output: 'sql/int@1';
				readonly nullable: true;
			};
			readonly 'sql/text@1': {
				readonly output: 'sql/text@1';
				readonly nullable: true;
			};
			readonly 'sql/varchar@1': {
				readonly output: 'pg/text@1';
				readonly nullable: true;
			};
		};
	};
	readonly sum: {
		readonly byCodec: {
			readonly 'pg/float@1': {
				readonly output: 'pg/float8@1';
				readonly nullable: true;
			};
			readonly 'pg/float4@1': {
				readonly output: 'pg/float4@1';
				readonly nullable: true;
			};
			readonly 'pg/float8@1': {
				readonly output: 'pg/float8@1';
				readonly nullable: true;
			};
			readonly 'pg/int@1': {
				readonly output: 'pg/int8number@1';
				readonly nullable: true;
			};
			readonly 'pg/int2@1': {
				readonly output: 'pg/int8number@1';
				readonly nullable: true;
			};
			readonly 'pg/int4@1': {
				readonly output: 'pg/int8number@1';
				readonly nullable: true;
			};
			readonly 'pg/int8@1': {
				readonly output: 'pg/int8number@1';
				readonly nullable: true;
			};
			readonly 'pg/int8number@1': {
				readonly output: 'pg/int8number@1';
				readonly nullable: true;
			};
			readonly 'pg/interval@1': {
				readonly output: 'pg/interval@1';
				readonly nullable: true;
			};
			readonly 'pg/numeric@1': {
				readonly output: 'pg/numeric@1';
				readonly nullable: true;
			};
			readonly 'pg/time-string@1': {
				readonly output: 'pg/interval@1';
				readonly nullable: true;
			};
			readonly 'pg/time-temporal@1': {
				readonly output: 'pg/interval@1';
				readonly nullable: true;
			};
			readonly 'pg/unboundedint@1': {
				readonly output: 'pg/unboundedint@1';
				readonly nullable: true;
			};
			readonly 'sql/float@1': {
				readonly output: 'pg/float8@1';
				readonly nullable: true;
			};
			readonly 'sql/int@1': {
				readonly output: 'pg/int8number@1';
				readonly nullable: true;
			};
		};
	};
	readonly sumBigInt: {
		readonly byCodec: {
			readonly 'pg/int@1': {
				readonly output: 'pg/int8@1';
				readonly nullable: true;
			};
			readonly 'pg/int2@1': {
				readonly output: 'pg/int8@1';
				readonly nullable: true;
			};
			readonly 'pg/int4@1': {
				readonly output: 'pg/int8@1';
				readonly nullable: true;
			};
			readonly 'pg/int8@1': {
				readonly output: 'pg/unboundedint@1';
				readonly nullable: true;
			};
			readonly 'pg/int8number@1': {
				readonly output: 'pg/unboundedint@1';
				readonly nullable: true;
			};
			readonly 'pg/unboundedint@1': {
				readonly output: 'pg/unboundedint@1';
				readonly nullable: true;
			};
			readonly 'sql/int@1': {
				readonly output: 'pg/int8@1';
				readonly nullable: true;
			};
		};
	};
};
type DefaultLiteralValue<
	CodecId extends string,
	Encoded,
> = CodecId extends keyof CodecTypes
	? Encoded extends CodecTypes[CodecId]['json']
		? Encoded
		: CodecTypes[CodecId]['json']
	: Encoded;

export type FieldOutputTypes = {
	readonly public: {
		readonly ChatLog: {
			readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
			readonly id: CodecTypes['pg/int4@1']['output'];
			readonly isHint: CodecTypes['pg/bool@1']['output'];
			readonly materialId: CodecTypes['pg/int4@1']['output'];
			readonly message: CodecTypes['pg/text@1']['output'];
			readonly sender: CodecTypes['pg/text@1']['output'];
			readonly studentId: CodecTypes['pg/int4@1']['output'];
			readonly toolCalled: CodecTypes['pg/bool@1']['output'];
		};
		readonly Material: {
			readonly content: CodecTypes['pg/json@1']['output'];
			readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
			readonly id: CodecTypes['pg/int4@1']['output'];
			readonly llmContextLayer: CodecTypes['pg/json@1']['output'];
			readonly order: CodecTypes['pg/int4@1']['output'];
			readonly subTopicId: CodecTypes['pg/int4@1']['output'];
			readonly title: CodecTypes['pg/text@1']['output'];
			readonly uiLayer: CodecTypes['pg/json@1']['output'];
			readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
		};
		readonly MaterialProgress: {
			readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
			readonly hintsUsed: CodecTypes['pg/int4@1']['output'];
			readonly id: CodecTypes['pg/int4@1']['output'];
			readonly isPassed: CodecTypes['pg/bool@1']['output'];
			readonly masteryScore: CodecTypes['pg/int4@1']['output'];
			readonly materialId: CodecTypes['pg/int4@1']['output'];
			readonly studentId: CodecTypes['pg/int4@1']['output'];
			readonly teacherFeedback: CodecTypes['pg/text@1']['output'] | null;
			readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
		};
		readonly SubTopic: {
			readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
			readonly id: CodecTypes['pg/int4@1']['output'];
			readonly name: CodecTypes['pg/text@1']['output'];
			readonly order: CodecTypes['pg/int4@1']['output'];
			readonly topicId: CodecTypes['pg/int4@1']['output'];
			readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
		};
		readonly Topic: {
			readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
			readonly difficultyLevel: CodecTypes['pg/int4@1']['output'];
			readonly id: CodecTypes['pg/int4@1']['output'];
			readonly name: CodecTypes['pg/text@1']['output'];
			readonly prerequisiteTopics: ReadonlyArray<
				CodecTypes['pg/int4@1']['output']
			>;
			readonly targetGrade: CodecTypes['pg/int4@1']['output'];
			readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
		};
		readonly User: {
			readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
			readonly grade: CodecTypes['pg/int4@1']['output'] | null;
			readonly id: CodecTypes['pg/int4@1']['output'];
			readonly isAdmin: CodecTypes['pg/bool@1']['output'];
			readonly name: CodecTypes['pg/text@1']['output'];
			readonly password: CodecTypes['pg/text@1']['output'];
			readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
			readonly username: CodecTypes['pg/text@1']['output'];
		};
	};
};
export type FieldInputTypes = {
	readonly public: {
		readonly ChatLog: {
			readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
			readonly id: CodecTypes['pg/int4@1']['input'];
			readonly isHint: CodecTypes['pg/bool@1']['input'];
			readonly materialId: CodecTypes['pg/int4@1']['input'];
			readonly message: CodecTypes['pg/text@1']['input'];
			readonly sender: CodecTypes['pg/text@1']['input'];
			readonly studentId: CodecTypes['pg/int4@1']['input'];
			readonly toolCalled: CodecTypes['pg/bool@1']['input'];
		};
		readonly Material: {
			readonly content: CodecTypes['pg/json@1']['input'];
			readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
			readonly id: CodecTypes['pg/int4@1']['input'];
			readonly llmContextLayer: CodecTypes['pg/json@1']['input'];
			readonly order: CodecTypes['pg/int4@1']['input'];
			readonly subTopicId: CodecTypes['pg/int4@1']['input'];
			readonly title: CodecTypes['pg/text@1']['input'];
			readonly uiLayer: CodecTypes['pg/json@1']['input'];
			readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
		};
		readonly MaterialProgress: {
			readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
			readonly hintsUsed: CodecTypes['pg/int4@1']['input'];
			readonly id: CodecTypes['pg/int4@1']['input'];
			readonly isPassed: CodecTypes['pg/bool@1']['input'];
			readonly masteryScore: CodecTypes['pg/int4@1']['input'];
			readonly materialId: CodecTypes['pg/int4@1']['input'];
			readonly studentId: CodecTypes['pg/int4@1']['input'];
			readonly teacherFeedback: CodecTypes['pg/text@1']['input'] | null;
			readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
		};
		readonly SubTopic: {
			readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
			readonly id: CodecTypes['pg/int4@1']['input'];
			readonly name: CodecTypes['pg/text@1']['input'];
			readonly order: CodecTypes['pg/int4@1']['input'];
			readonly topicId: CodecTypes['pg/int4@1']['input'];
			readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
		};
		readonly Topic: {
			readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
			readonly difficultyLevel: CodecTypes['pg/int4@1']['input'];
			readonly id: CodecTypes['pg/int4@1']['input'];
			readonly name: CodecTypes['pg/text@1']['input'];
			readonly prerequisiteTopics: ReadonlyArray<
				CodecTypes['pg/int4@1']['input']
			>;
			readonly targetGrade: CodecTypes['pg/int4@1']['input'];
			readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
		};
		readonly User: {
			readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
			readonly grade: CodecTypes['pg/int4@1']['input'] | null;
			readonly id: CodecTypes['pg/int4@1']['input'];
			readonly isAdmin: CodecTypes['pg/bool@1']['input'];
			readonly name: CodecTypes['pg/text@1']['input'];
			readonly password: CodecTypes['pg/text@1']['input'];
			readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
			readonly username: CodecTypes['pg/text@1']['input'];
		};
	};
};
export type StorageColumnTypes = {
	readonly public: {
		readonly ChatLog: {
			readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
			readonly id: CodecTypes['pg/int4@1']['output'];
			readonly isHint: CodecTypes['pg/bool@1']['output'];
			readonly materialId: CodecTypes['pg/int4@1']['output'];
			readonly message: CodecTypes['pg/text@1']['output'];
			readonly sender: CodecTypes['pg/text@1']['output'];
			readonly studentId: CodecTypes['pg/int4@1']['output'];
			readonly toolCalled: CodecTypes['pg/bool@1']['output'];
		};
		readonly Material: {
			readonly content: CodecTypes['pg/json@1']['output'];
			readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
			readonly id: CodecTypes['pg/int4@1']['output'];
			readonly llmContextLayer: CodecTypes['pg/json@1']['output'];
			readonly order: CodecTypes['pg/int4@1']['output'];
			readonly subTopicId: CodecTypes['pg/int4@1']['output'];
			readonly title: CodecTypes['pg/text@1']['output'];
			readonly uiLayer: CodecTypes['pg/json@1']['output'];
			readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
		};
		readonly MaterialProgress: {
			readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
			readonly hintsUsed: CodecTypes['pg/int4@1']['output'];
			readonly id: CodecTypes['pg/int4@1']['output'];
			readonly isPassed: CodecTypes['pg/bool@1']['output'];
			readonly masteryScore: CodecTypes['pg/int4@1']['output'];
			readonly materialId: CodecTypes['pg/int4@1']['output'];
			readonly studentId: CodecTypes['pg/int4@1']['output'];
			readonly teacherFeedback: CodecTypes['pg/text@1']['output'] | null;
			readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
		};
		readonly SubTopic: {
			readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
			readonly id: CodecTypes['pg/int4@1']['output'];
			readonly name: CodecTypes['pg/text@1']['output'];
			readonly order: CodecTypes['pg/int4@1']['output'];
			readonly topicId: CodecTypes['pg/int4@1']['output'];
			readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
		};
		readonly Topic: {
			readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
			readonly difficultyLevel: CodecTypes['pg/int4@1']['output'];
			readonly id: CodecTypes['pg/int4@1']['output'];
			readonly name: CodecTypes['pg/text@1']['output'];
			readonly prerequisiteTopics: ReadonlyArray<
				CodecTypes['pg/int4@1']['output']
			>;
			readonly targetGrade: CodecTypes['pg/int4@1']['output'];
			readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
		};
		readonly User: {
			readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
			readonly grade: CodecTypes['pg/int4@1']['output'] | null;
			readonly id: CodecTypes['pg/int4@1']['output'];
			readonly isAdmin: CodecTypes['pg/bool@1']['output'];
			readonly name: CodecTypes['pg/text@1']['output'];
			readonly password: CodecTypes['pg/text@1']['output'];
			readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
			readonly username: CodecTypes['pg/text@1']['output'];
		};
	};
};
export type StorageColumnInputTypes = {
	readonly public: {
		readonly ChatLog: {
			readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
			readonly id: CodecTypes['pg/int4@1']['input'];
			readonly isHint: CodecTypes['pg/bool@1']['input'];
			readonly materialId: CodecTypes['pg/int4@1']['input'];
			readonly message: CodecTypes['pg/text@1']['input'];
			readonly sender: CodecTypes['pg/text@1']['input'];
			readonly studentId: CodecTypes['pg/int4@1']['input'];
			readonly toolCalled: CodecTypes['pg/bool@1']['input'];
		};
		readonly Material: {
			readonly content: CodecTypes['pg/json@1']['input'];
			readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
			readonly id: CodecTypes['pg/int4@1']['input'];
			readonly llmContextLayer: CodecTypes['pg/json@1']['input'];
			readonly order: CodecTypes['pg/int4@1']['input'];
			readonly subTopicId: CodecTypes['pg/int4@1']['input'];
			readonly title: CodecTypes['pg/text@1']['input'];
			readonly uiLayer: CodecTypes['pg/json@1']['input'];
			readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
		};
		readonly MaterialProgress: {
			readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
			readonly hintsUsed: CodecTypes['pg/int4@1']['input'];
			readonly id: CodecTypes['pg/int4@1']['input'];
			readonly isPassed: CodecTypes['pg/bool@1']['input'];
			readonly masteryScore: CodecTypes['pg/int4@1']['input'];
			readonly materialId: CodecTypes['pg/int4@1']['input'];
			readonly studentId: CodecTypes['pg/int4@1']['input'];
			readonly teacherFeedback: CodecTypes['pg/text@1']['input'] | null;
			readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
		};
		readonly SubTopic: {
			readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
			readonly id: CodecTypes['pg/int4@1']['input'];
			readonly name: CodecTypes['pg/text@1']['input'];
			readonly order: CodecTypes['pg/int4@1']['input'];
			readonly topicId: CodecTypes['pg/int4@1']['input'];
			readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
		};
		readonly Topic: {
			readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
			readonly difficultyLevel: CodecTypes['pg/int4@1']['input'];
			readonly id: CodecTypes['pg/int4@1']['input'];
			readonly name: CodecTypes['pg/text@1']['input'];
			readonly prerequisiteTopics: ReadonlyArray<
				CodecTypes['pg/int4@1']['input']
			>;
			readonly targetGrade: CodecTypes['pg/int4@1']['input'];
			readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
		};
		readonly User: {
			readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
			readonly grade: CodecTypes['pg/int4@1']['input'] | null;
			readonly id: CodecTypes['pg/int4@1']['input'];
			readonly isAdmin: CodecTypes['pg/bool@1']['input'];
			readonly name: CodecTypes['pg/text@1']['input'];
			readonly password: CodecTypes['pg/text@1']['input'];
			readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
			readonly username: CodecTypes['pg/text@1']['input'];
		};
	};
};

export namespace Models {
	export type public_ChatLog = {
		createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
		id: CodecTypes['pg/int4@1']['output'];
		isHint: CodecTypes['pg/bool@1']['output'];
		materialId: CodecTypes['pg/int4@1']['output'];
		message: CodecTypes['pg/text@1']['output'];
		sender: CodecTypes['pg/text@1']['output'];
		studentId: CodecTypes['pg/int4@1']['output'];
		toolCalled: CodecTypes['pg/bool@1']['output'];
		material: public_Material;
		student: public_User;
		readonly [RelationKeys]?: 'material' | 'student';
	};
	export type public_Material = {
		content: CodecTypes['pg/json@1']['output'];
		createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
		id: CodecTypes['pg/int4@1']['output'];
		llmContextLayer: CodecTypes['pg/json@1']['output'];
		order: CodecTypes['pg/int4@1']['output'];
		subTopicId: CodecTypes['pg/int4@1']['output'];
		title: CodecTypes['pg/text@1']['output'];
		uiLayer: CodecTypes['pg/json@1']['output'];
		updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
		chatLogs: public_ChatLog[];
		progresses: public_MaterialProgress[];
		subTopic: public_SubTopic;
		readonly [RelationKeys]?: 'chatLogs' | 'progresses' | 'subTopic';
	};
	export type public_MaterialProgress = {
		createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
		hintsUsed: CodecTypes['pg/int4@1']['output'];
		id: CodecTypes['pg/int4@1']['output'];
		isPassed: CodecTypes['pg/bool@1']['output'];
		masteryScore: CodecTypes['pg/int4@1']['output'];
		materialId: CodecTypes['pg/int4@1']['output'];
		studentId: CodecTypes['pg/int4@1']['output'];
		teacherFeedback: CodecTypes['pg/text@1']['output'] | null;
		updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
		material: public_Material;
		student: public_User;
		readonly [RelationKeys]?: 'material' | 'student';
	};
	export type public_SubTopic = {
		createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
		id: CodecTypes['pg/int4@1']['output'];
		name: CodecTypes['pg/text@1']['output'];
		order: CodecTypes['pg/int4@1']['output'];
		topicId: CodecTypes['pg/int4@1']['output'];
		updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
		materials: public_Material[];
		topic: public_Topic;
		readonly [RelationKeys]?: 'materials' | 'topic';
	};
	export type public_Topic = {
		createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
		difficultyLevel: CodecTypes['pg/int4@1']['output'];
		id: CodecTypes['pg/int4@1']['output'];
		name: CodecTypes['pg/text@1']['output'];
		prerequisiteTopics: ReadonlyArray<CodecTypes['pg/int4@1']['output']>;
		targetGrade: CodecTypes['pg/int4@1']['output'];
		updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
		subTopics: public_SubTopic[];
		readonly [RelationKeys]?: 'subTopics';
	};
	export type public_User = {
		createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
		grade: CodecTypes['pg/int4@1']['output'] | null;
		id: CodecTypes['pg/int4@1']['output'];
		isAdmin: CodecTypes['pg/bool@1']['output'];
		name: CodecTypes['pg/text@1']['output'];
		password: CodecTypes['pg/text@1']['output'];
		updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
		username: CodecTypes['pg/text@1']['output'];
		chatLogs: public_ChatLog[];
		progresses: public_MaterialProgress[];
		readonly [RelationKeys]?: 'chatLogs' | 'progresses';
	};
}

export declare const models: {
	public: {
		ChatLog: Models.public_ChatLog;
		Material: Models.public_Material;
		MaterialProgress: Models.public_MaterialProgress;
		SubTopic: Models.public_SubTopic;
		Topic: Models.public_Topic;
		User: Models.public_User;
	};
};

export type TypeMaps = TypeMapsType<
	CodecTypes,
	QueryOperationTypes,
	FieldOutputTypes,
	FieldInputTypes,
	StorageColumnTypes,
	StorageColumnInputTypes,
	AggregateTypes
>;

type ContractBase = Omit<
	ContractType<{
		readonly namespaces: {
			readonly public: {
				readonly id: 'public';
				readonly kind: 'postgres-schema';
				readonly entries: {
					readonly table: {
						readonly ChatLog: {
							columns: {
								readonly createdAt: {
									readonly nativeType: 'timestamptz';
									readonly codecId: 'pg/timestamptz-temporal@1';
									readonly nullable: false;
									readonly default: {
										readonly kind: 'function';
										readonly expression: 'now()';
									};
								};
								readonly id: {
									readonly nativeType: 'int4';
									readonly codecId: 'pg/int4@1';
									readonly nullable: false;
									readonly default: {
										readonly kind: 'function';
										readonly expression: 'autoincrement()';
									};
								};
								readonly isHint: {
									readonly nativeType: 'bool';
									readonly codecId: 'pg/bool@1';
									readonly nullable: false;
									readonly default: {
										readonly kind: 'literal';
										readonly value: DefaultLiteralValue<
											'pg/bool@1',
											false
										>;
									};
								};
								readonly materialId: {
									readonly nativeType: 'int4';
									readonly codecId: 'pg/int4@1';
									readonly nullable: false;
								};
								readonly message: {
									readonly nativeType: 'text';
									readonly codecId: 'pg/text@1';
									readonly nullable: false;
								};
								readonly sender: {
									readonly nativeType: 'text';
									readonly codecId: 'pg/text@1';
									readonly nullable: false;
								};
								readonly studentId: {
									readonly nativeType: 'int4';
									readonly codecId: 'pg/int4@1';
									readonly nullable: false;
								};
								readonly toolCalled: {
									readonly nativeType: 'bool';
									readonly codecId: 'pg/bool@1';
									readonly nullable: false;
									readonly default: {
										readonly kind: 'literal';
										readonly value: DefaultLiteralValue<
											'pg/bool@1',
											false
										>;
									};
								};
							};
							primaryKey: { readonly columns: readonly ['id'] };
							uniques: readonly [];
							indexes: readonly [
								{
									readonly name: 'ChatLog_materialId_idx_e0f85a6d';
									readonly prefix: 'ChatLog_materialId_idx';
									readonly columns: readonly ['materialId'];
									readonly unique: false;
								},
								{
									readonly name: 'ChatLog_studentId_idx_bf255322';
									readonly prefix: 'ChatLog_studentId_idx';
									readonly columns: readonly ['studentId'];
									readonly unique: false;
								},
							];
							foreignKeys: readonly [
								{
									readonly source: {
										readonly namespaceId: 'public' &
											NamespaceId;
										readonly tableName: 'ChatLog';
										readonly columns: readonly [
											'studentId',
										];
									};
									readonly target: {
										readonly namespaceId: 'public' &
											NamespaceId;
										readonly tableName: 'User';
										readonly columns: readonly ['id'];
									};
								},
								{
									readonly source: {
										readonly namespaceId: 'public' &
											NamespaceId;
										readonly tableName: 'ChatLog';
										readonly columns: readonly [
											'materialId',
										];
									};
									readonly target: {
										readonly namespaceId: 'public' &
											NamespaceId;
										readonly tableName: 'Material';
										readonly columns: readonly ['id'];
									};
								},
							];
						};
						readonly Material: {
							columns: {
								readonly content: {
									readonly nativeType: 'json';
									readonly codecId: 'pg/json@1';
									readonly nullable: false;
								};
								readonly createdAt: {
									readonly nativeType: 'timestamptz';
									readonly codecId: 'pg/timestamptz-temporal@1';
									readonly nullable: false;
									readonly default: {
										readonly kind: 'function';
										readonly expression: 'now()';
									};
								};
								readonly id: {
									readonly nativeType: 'int4';
									readonly codecId: 'pg/int4@1';
									readonly nullable: false;
									readonly default: {
										readonly kind: 'function';
										readonly expression: 'autoincrement()';
									};
								};
								readonly llmContextLayer: {
									readonly nativeType: 'json';
									readonly codecId: 'pg/json@1';
									readonly nullable: false;
								};
								readonly order: {
									readonly nativeType: 'int4';
									readonly codecId: 'pg/int4@1';
									readonly nullable: false;
								};
								readonly subTopicId: {
									readonly nativeType: 'int4';
									readonly codecId: 'pg/int4@1';
									readonly nullable: false;
								};
								readonly title: {
									readonly nativeType: 'text';
									readonly codecId: 'pg/text@1';
									readonly nullable: false;
								};
								readonly uiLayer: {
									readonly nativeType: 'json';
									readonly codecId: 'pg/json@1';
									readonly nullable: false;
								};
								readonly updatedAt: {
									readonly nativeType: 'timestamptz';
									readonly codecId: 'pg/timestamptz-temporal@1';
									readonly nullable: false;
									readonly default: {
										readonly kind: 'function';
										readonly expression: 'now()';
									};
								};
							};
							primaryKey: { readonly columns: readonly ['id'] };
							uniques: readonly [];
							indexes: readonly [
								{
									readonly name: 'Material_subTopicId_idx_627371a0';
									readonly prefix: 'Material_subTopicId_idx';
									readonly columns: readonly ['subTopicId'];
									readonly unique: false;
								},
							];
							foreignKeys: readonly [
								{
									readonly source: {
										readonly namespaceId: 'public' &
											NamespaceId;
										readonly tableName: 'Material';
										readonly columns: readonly [
											'subTopicId',
										];
									};
									readonly target: {
										readonly namespaceId: 'public' &
											NamespaceId;
										readonly tableName: 'SubTopic';
										readonly columns: readonly ['id'];
									};
								},
							];
						};
						readonly MaterialProgress: {
							columns: {
								readonly createdAt: {
									readonly nativeType: 'timestamptz';
									readonly codecId: 'pg/timestamptz-temporal@1';
									readonly nullable: false;
									readonly default: {
										readonly kind: 'function';
										readonly expression: 'now()';
									};
								};
								readonly hintsUsed: {
									readonly nativeType: 'int4';
									readonly codecId: 'pg/int4@1';
									readonly nullable: false;
									readonly default: {
										readonly kind: 'literal';
										readonly value: DefaultLiteralValue<
											'pg/int4@1',
											0
										>;
									};
								};
								readonly id: {
									readonly nativeType: 'int4';
									readonly codecId: 'pg/int4@1';
									readonly nullable: false;
									readonly default: {
										readonly kind: 'function';
										readonly expression: 'autoincrement()';
									};
								};
								readonly isPassed: {
									readonly nativeType: 'bool';
									readonly codecId: 'pg/bool@1';
									readonly nullable: false;
									readonly default: {
										readonly kind: 'literal';
										readonly value: DefaultLiteralValue<
											'pg/bool@1',
											false
										>;
									};
								};
								readonly masteryScore: {
									readonly nativeType: 'int4';
									readonly codecId: 'pg/int4@1';
									readonly nullable: false;
									readonly default: {
										readonly kind: 'literal';
										readonly value: DefaultLiteralValue<
											'pg/int4@1',
											0
										>;
									};
								};
								readonly materialId: {
									readonly nativeType: 'int4';
									readonly codecId: 'pg/int4@1';
									readonly nullable: false;
								};
								readonly studentId: {
									readonly nativeType: 'int4';
									readonly codecId: 'pg/int4@1';
									readonly nullable: false;
								};
								readonly teacherFeedback: {
									readonly nativeType: 'text';
									readonly codecId: 'pg/text@1';
									readonly nullable: true;
								};
								readonly updatedAt: {
									readonly nativeType: 'timestamptz';
									readonly codecId: 'pg/timestamptz-temporal@1';
									readonly nullable: false;
									readonly default: {
										readonly kind: 'function';
										readonly expression: 'now()';
									};
								};
							};
							primaryKey: { readonly columns: readonly ['id'] };
							uniques: readonly [
								{
									readonly columns: readonly [
										'studentId',
										'materialId',
									];
								},
							];
							indexes: readonly [
								{
									readonly name: 'MaterialProgress_materialId_idx_e0f85a6d';
									readonly prefix: 'MaterialProgress_materialId_idx';
									readonly columns: readonly ['materialId'];
									readonly unique: false;
								},
								{
									readonly name: 'MaterialProgress_studentId_idx_bf255322';
									readonly prefix: 'MaterialProgress_studentId_idx';
									readonly columns: readonly ['studentId'];
									readonly unique: false;
								},
							];
							foreignKeys: readonly [
								{
									readonly source: {
										readonly namespaceId: 'public' &
											NamespaceId;
										readonly tableName: 'MaterialProgress';
										readonly columns: readonly [
											'studentId',
										];
									};
									readonly target: {
										readonly namespaceId: 'public' &
											NamespaceId;
										readonly tableName: 'User';
										readonly columns: readonly ['id'];
									};
								},
								{
									readonly source: {
										readonly namespaceId: 'public' &
											NamespaceId;
										readonly tableName: 'MaterialProgress';
										readonly columns: readonly [
											'materialId',
										];
									};
									readonly target: {
										readonly namespaceId: 'public' &
											NamespaceId;
										readonly tableName: 'Material';
										readonly columns: readonly ['id'];
									};
								},
							];
						};
						readonly SubTopic: {
							columns: {
								readonly createdAt: {
									readonly nativeType: 'timestamptz';
									readonly codecId: 'pg/timestamptz-temporal@1';
									readonly nullable: false;
									readonly default: {
										readonly kind: 'function';
										readonly expression: 'now()';
									};
								};
								readonly id: {
									readonly nativeType: 'int4';
									readonly codecId: 'pg/int4@1';
									readonly nullable: false;
									readonly default: {
										readonly kind: 'function';
										readonly expression: 'autoincrement()';
									};
								};
								readonly name: {
									readonly nativeType: 'text';
									readonly codecId: 'pg/text@1';
									readonly nullable: false;
								};
								readonly order: {
									readonly nativeType: 'int4';
									readonly codecId: 'pg/int4@1';
									readonly nullable: false;
								};
								readonly topicId: {
									readonly nativeType: 'int4';
									readonly codecId: 'pg/int4@1';
									readonly nullable: false;
								};
								readonly updatedAt: {
									readonly nativeType: 'timestamptz';
									readonly codecId: 'pg/timestamptz-temporal@1';
									readonly nullable: false;
									readonly default: {
										readonly kind: 'function';
										readonly expression: 'now()';
									};
								};
							};
							primaryKey: { readonly columns: readonly ['id'] };
							uniques: readonly [];
							indexes: readonly [
								{
									readonly name: 'SubTopic_topicId_idx_6f05808f';
									readonly prefix: 'SubTopic_topicId_idx';
									readonly columns: readonly ['topicId'];
									readonly unique: false;
								},
							];
							foreignKeys: readonly [
								{
									readonly source: {
										readonly namespaceId: 'public' &
											NamespaceId;
										readonly tableName: 'SubTopic';
										readonly columns: readonly ['topicId'];
									};
									readonly target: {
										readonly namespaceId: 'public' &
											NamespaceId;
										readonly tableName: 'Topic';
										readonly columns: readonly ['id'];
									};
								},
							];
						};
						readonly Topic: {
							columns: {
								readonly createdAt: {
									readonly nativeType: 'timestamptz';
									readonly codecId: 'pg/timestamptz-temporal@1';
									readonly nullable: false;
									readonly default: {
										readonly kind: 'function';
										readonly expression: 'now()';
									};
								};
								readonly difficultyLevel: {
									readonly nativeType: 'int4';
									readonly codecId: 'pg/int4@1';
									readonly nullable: false;
								};
								readonly id: {
									readonly nativeType: 'int4';
									readonly codecId: 'pg/int4@1';
									readonly nullable: false;
									readonly default: {
										readonly kind: 'function';
										readonly expression: 'autoincrement()';
									};
								};
								readonly name: {
									readonly nativeType: 'text';
									readonly codecId: 'pg/text@1';
									readonly nullable: false;
								};
								readonly prerequisiteTopics: {
									readonly nativeType: 'int4';
									readonly codecId: 'pg/int4@1';
									readonly nullable: false;
								};
								readonly targetGrade: {
									readonly nativeType: 'int4';
									readonly codecId: 'pg/int4@1';
									readonly nullable: false;
								};
								readonly updatedAt: {
									readonly nativeType: 'timestamptz';
									readonly codecId: 'pg/timestamptz-temporal@1';
									readonly nullable: false;
									readonly default: {
										readonly kind: 'function';
										readonly expression: 'now()';
									};
								};
							};
							primaryKey: { readonly columns: readonly ['id'] };
							uniques: readonly [];
							indexes: readonly [];
							foreignKeys: readonly [];
						};
						readonly User: {
							columns: {
								readonly createdAt: {
									readonly nativeType: 'timestamptz';
									readonly codecId: 'pg/timestamptz-temporal@1';
									readonly nullable: false;
									readonly default: {
										readonly kind: 'function';
										readonly expression: 'now()';
									};
								};
								readonly grade: {
									readonly nativeType: 'int4';
									readonly codecId: 'pg/int4@1';
									readonly nullable: true;
								};
								readonly id: {
									readonly nativeType: 'int4';
									readonly codecId: 'pg/int4@1';
									readonly nullable: false;
									readonly default: {
										readonly kind: 'function';
										readonly expression: 'autoincrement()';
									};
								};
								readonly isAdmin: {
									readonly nativeType: 'bool';
									readonly codecId: 'pg/bool@1';
									readonly nullable: false;
									readonly default: {
										readonly kind: 'literal';
										readonly value: DefaultLiteralValue<
											'pg/bool@1',
											false
										>;
									};
								};
								readonly name: {
									readonly nativeType: 'text';
									readonly codecId: 'pg/text@1';
									readonly nullable: false;
								};
								readonly password: {
									readonly nativeType: 'text';
									readonly codecId: 'pg/text@1';
									readonly nullable: false;
								};
								readonly updatedAt: {
									readonly nativeType: 'timestamptz';
									readonly codecId: 'pg/timestamptz-temporal@1';
									readonly nullable: false;
									readonly default: {
										readonly kind: 'function';
										readonly expression: 'now()';
									};
								};
								readonly username: {
									readonly nativeType: 'text';
									readonly codecId: 'pg/text@1';
									readonly nullable: false;
								};
							};
							primaryKey: { readonly columns: readonly ['id'] };
							uniques: readonly [
								{ readonly columns: readonly ['username'] },
							];
							indexes: readonly [];
							foreignKeys: readonly [];
						};
					};
				};
			};
		};
		readonly storageHash: StorageHash;
	}>,
	'roots' | 'domain'
> & {
	readonly target: 'postgres';
	readonly targetFamily: 'sql';
	readonly roots: {
		readonly ChatLog: {
			readonly namespace: 'public' & NamespaceId;
			readonly model: 'ChatLog';
		};
		readonly Material: {
			readonly namespace: 'public' & NamespaceId;
			readonly model: 'Material';
		};
		readonly MaterialProgress: {
			readonly namespace: 'public' & NamespaceId;
			readonly model: 'MaterialProgress';
		};
		readonly SubTopic: {
			readonly namespace: 'public' & NamespaceId;
			readonly model: 'SubTopic';
		};
		readonly Topic: {
			readonly namespace: 'public' & NamespaceId;
			readonly model: 'Topic';
		};
		readonly User: {
			readonly namespace: 'public' & NamespaceId;
			readonly model: 'User';
		};
	};
	readonly domain: {
		readonly namespaces: {
			readonly public: {
				readonly models: {
					readonly ChatLog: {
						readonly fields: {
							readonly createdAt: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/timestamptz-temporal@1';
								};
							};
							readonly id: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/int4@1';
								};
							};
							readonly isHint: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/bool@1';
								};
							};
							readonly materialId: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/int4@1';
								};
							};
							readonly message: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/text@1';
								};
							};
							readonly sender: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/text@1';
								};
							};
							readonly studentId: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/int4@1';
								};
							};
							readonly toolCalled: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/bool@1';
								};
							};
						};
						readonly relations: {
							readonly material: {
								readonly to: {
									readonly namespace: 'public' & NamespaceId;
									readonly model: 'Material';
								};
								readonly cardinality: 'N:1';
								readonly nullable: false;
								readonly on: {
									readonly localFields: readonly [
										'materialId',
									];
									readonly targetFields: readonly ['id'];
								};
							};
							readonly student: {
								readonly to: {
									readonly namespace: 'public' & NamespaceId;
									readonly model: 'User';
								};
								readonly cardinality: 'N:1';
								readonly nullable: false;
								readonly on: {
									readonly localFields: readonly [
										'studentId',
									];
									readonly targetFields: readonly ['id'];
								};
							};
						};
						readonly storage: {
							readonly table: 'ChatLog';
							readonly namespaceId: 'public';
							readonly fields: {
								readonly createdAt: {
									readonly column: 'createdAt';
								};
								readonly id: { readonly column: 'id' };
								readonly isHint: { readonly column: 'isHint' };
								readonly materialId: {
									readonly column: 'materialId';
								};
								readonly message: {
									readonly column: 'message';
								};
								readonly sender: { readonly column: 'sender' };
								readonly studentId: {
									readonly column: 'studentId';
								};
								readonly toolCalled: {
									readonly column: 'toolCalled';
								};
							};
						};
					};
					readonly Material: {
						readonly fields: {
							readonly content: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/json@1';
								};
							};
							readonly createdAt: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/timestamptz-temporal@1';
								};
							};
							readonly id: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/int4@1';
								};
							};
							readonly llmContextLayer: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/json@1';
								};
							};
							readonly order: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/int4@1';
								};
							};
							readonly subTopicId: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/int4@1';
								};
							};
							readonly title: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/text@1';
								};
							};
							readonly uiLayer: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/json@1';
								};
							};
							readonly updatedAt: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/timestamptz-temporal@1';
								};
							};
						};
						readonly relations: {
							readonly chatLogs: {
								readonly to: {
									readonly namespace: 'public' & NamespaceId;
									readonly model: 'ChatLog';
								};
								readonly cardinality: '1:N';
								readonly on: {
									readonly localFields: readonly ['id'];
									readonly targetFields: readonly [
										'materialId',
									];
								};
							};
							readonly progresses: {
								readonly to: {
									readonly namespace: 'public' & NamespaceId;
									readonly model: 'MaterialProgress';
								};
								readonly cardinality: '1:N';
								readonly on: {
									readonly localFields: readonly ['id'];
									readonly targetFields: readonly [
										'materialId',
									];
								};
							};
							readonly subTopic: {
								readonly to: {
									readonly namespace: 'public' & NamespaceId;
									readonly model: 'SubTopic';
								};
								readonly cardinality: 'N:1';
								readonly nullable: false;
								readonly on: {
									readonly localFields: readonly [
										'subTopicId',
									];
									readonly targetFields: readonly ['id'];
								};
							};
						};
						readonly storage: {
							readonly table: 'Material';
							readonly namespaceId: 'public';
							readonly fields: {
								readonly content: {
									readonly column: 'content';
								};
								readonly createdAt: {
									readonly column: 'createdAt';
								};
								readonly id: { readonly column: 'id' };
								readonly llmContextLayer: {
									readonly column: 'llmContextLayer';
								};
								readonly order: { readonly column: 'order' };
								readonly subTopicId: {
									readonly column: 'subTopicId';
								};
								readonly title: { readonly column: 'title' };
								readonly uiLayer: {
									readonly column: 'uiLayer';
								};
								readonly updatedAt: {
									readonly column: 'updatedAt';
								};
							};
						};
					};
					readonly MaterialProgress: {
						readonly fields: {
							readonly createdAt: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/timestamptz-temporal@1';
								};
							};
							readonly hintsUsed: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/int4@1';
								};
							};
							readonly id: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/int4@1';
								};
							};
							readonly isPassed: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/bool@1';
								};
							};
							readonly masteryScore: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/int4@1';
								};
							};
							readonly materialId: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/int4@1';
								};
							};
							readonly studentId: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/int4@1';
								};
							};
							readonly teacherFeedback: {
								readonly nullable: true;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/text@1';
								};
							};
							readonly updatedAt: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/timestamptz-temporal@1';
								};
							};
						};
						readonly relations: {
							readonly material: {
								readonly to: {
									readonly namespace: 'public' & NamespaceId;
									readonly model: 'Material';
								};
								readonly cardinality: 'N:1';
								readonly nullable: false;
								readonly on: {
									readonly localFields: readonly [
										'materialId',
									];
									readonly targetFields: readonly ['id'];
								};
							};
							readonly student: {
								readonly to: {
									readonly namespace: 'public' & NamespaceId;
									readonly model: 'User';
								};
								readonly cardinality: 'N:1';
								readonly nullable: false;
								readonly on: {
									readonly localFields: readonly [
										'studentId',
									];
									readonly targetFields: readonly ['id'];
								};
							};
						};
						readonly storage: {
							readonly table: 'MaterialProgress';
							readonly namespaceId: 'public';
							readonly fields: {
								readonly createdAt: {
									readonly column: 'createdAt';
								};
								readonly hintsUsed: {
									readonly column: 'hintsUsed';
								};
								readonly id: { readonly column: 'id' };
								readonly isPassed: {
									readonly column: 'isPassed';
								};
								readonly masteryScore: {
									readonly column: 'masteryScore';
								};
								readonly materialId: {
									readonly column: 'materialId';
								};
								readonly studentId: {
									readonly column: 'studentId';
								};
								readonly teacherFeedback: {
									readonly column: 'teacherFeedback';
								};
								readonly updatedAt: {
									readonly column: 'updatedAt';
								};
							};
						};
					};
					readonly SubTopic: {
						readonly fields: {
							readonly createdAt: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/timestamptz-temporal@1';
								};
							};
							readonly id: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/int4@1';
								};
							};
							readonly name: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/text@1';
								};
							};
							readonly order: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/int4@1';
								};
							};
							readonly topicId: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/int4@1';
								};
							};
							readonly updatedAt: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/timestamptz-temporal@1';
								};
							};
						};
						readonly relations: {
							readonly materials: {
								readonly to: {
									readonly namespace: 'public' & NamespaceId;
									readonly model: 'Material';
								};
								readonly cardinality: '1:N';
								readonly on: {
									readonly localFields: readonly ['id'];
									readonly targetFields: readonly [
										'subTopicId',
									];
								};
							};
							readonly topic: {
								readonly to: {
									readonly namespace: 'public' & NamespaceId;
									readonly model: 'Topic';
								};
								readonly cardinality: 'N:1';
								readonly nullable: false;
								readonly on: {
									readonly localFields: readonly ['topicId'];
									readonly targetFields: readonly ['id'];
								};
							};
						};
						readonly storage: {
							readonly table: 'SubTopic';
							readonly namespaceId: 'public';
							readonly fields: {
								readonly createdAt: {
									readonly column: 'createdAt';
								};
								readonly id: { readonly column: 'id' };
								readonly name: { readonly column: 'name' };
								readonly order: { readonly column: 'order' };
								readonly topicId: {
									readonly column: 'topicId';
								};
								readonly updatedAt: {
									readonly column: 'updatedAt';
								};
							};
						};
					};
					readonly Topic: {
						readonly fields: {
							readonly createdAt: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/timestamptz-temporal@1';
								};
							};
							readonly difficultyLevel: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/int4@1';
								};
							};
							readonly id: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/int4@1';
								};
							};
							readonly name: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/text@1';
								};
							};
							readonly prerequisiteTopics: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/int4@1';
								};
								readonly many: true;
							};
							readonly targetGrade: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/int4@1';
								};
							};
							readonly updatedAt: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/timestamptz-temporal@1';
								};
							};
						};
						readonly relations: {
							readonly subTopics: {
								readonly to: {
									readonly namespace: 'public' & NamespaceId;
									readonly model: 'SubTopic';
								};
								readonly cardinality: '1:N';
								readonly on: {
									readonly localFields: readonly ['id'];
									readonly targetFields: readonly ['topicId'];
								};
							};
						};
						readonly storage: {
							readonly table: 'Topic';
							readonly namespaceId: 'public';
							readonly fields: {
								readonly createdAt: {
									readonly column: 'createdAt';
								};
								readonly difficultyLevel: {
									readonly column: 'difficultyLevel';
								};
								readonly id: { readonly column: 'id' };
								readonly name: { readonly column: 'name' };
								readonly prerequisiteTopics: {
									readonly column: 'prerequisiteTopics';
								};
								readonly targetGrade: {
									readonly column: 'targetGrade';
								};
								readonly updatedAt: {
									readonly column: 'updatedAt';
								};
							};
						};
					};
					readonly User: {
						readonly fields: {
							readonly createdAt: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/timestamptz-temporal@1';
								};
							};
							readonly grade: {
								readonly nullable: true;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/int4@1';
								};
							};
							readonly id: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/int4@1';
								};
							};
							readonly isAdmin: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/bool@1';
								};
							};
							readonly name: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/text@1';
								};
							};
							readonly password: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/text@1';
								};
							};
							readonly updatedAt: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/timestamptz-temporal@1';
								};
							};
							readonly username: {
								readonly nullable: false;
								readonly type: {
									readonly kind: 'scalar';
									readonly codecId: 'pg/text@1';
								};
							};
						};
						readonly relations: {
							readonly chatLogs: {
								readonly to: {
									readonly namespace: 'public' & NamespaceId;
									readonly model: 'ChatLog';
								};
								readonly cardinality: '1:N';
								readonly on: {
									readonly localFields: readonly ['id'];
									readonly targetFields: readonly [
										'studentId',
									];
								};
							};
							readonly progresses: {
								readonly to: {
									readonly namespace: 'public' & NamespaceId;
									readonly model: 'MaterialProgress';
								};
								readonly cardinality: '1:N';
								readonly on: {
									readonly localFields: readonly ['id'];
									readonly targetFields: readonly [
										'studentId',
									];
								};
							};
						};
						readonly storage: {
							readonly table: 'User';
							readonly namespaceId: 'public';
							readonly fields: {
								readonly createdAt: {
									readonly column: 'createdAt';
								};
								readonly grade: { readonly column: 'grade' };
								readonly id: { readonly column: 'id' };
								readonly isAdmin: {
									readonly column: 'isAdmin';
								};
								readonly name: { readonly column: 'name' };
								readonly password: {
									readonly column: 'password';
								};
								readonly updatedAt: {
									readonly column: 'updatedAt';
								};
								readonly username: {
									readonly column: 'username';
								};
							};
						};
					};
				};
			};
		};
	};
	readonly capabilities: {
		readonly postgres: {
			readonly distinctOn: true;
			readonly jsonAgg: true;
			readonly lateral: true;
			readonly limit: true;
			readonly orderBy: true;
			readonly returning: true;
		};
		readonly sql: {
			readonly checkConstraint: true;
			readonly defaultInInsert: true;
			readonly enums: true;
			readonly insertOnConflictSkip: true;
			readonly insertOnConflictWithoutTarget: true;
			readonly lateral: true;
			readonly returning: true;
			readonly scalarList: true;
		};
	};
	readonly extensions: {};
	readonly meta: {};

	readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
